Oridgin code1
avalon-dev-j110/laboratornaya-rabota-no1-Lena-Helen17 pull request #1
Opened 2020-04-06 07:42 UTC by Lena-Helen17

Лаба №1 на сдачу. Не знаю, что я там напушила.

2020-04-08 20:32 UTC, KolosovKD requested changes
Код приличный, немного не соблюдены условия.
Обращайте внимание на комментарии.

По условиям предполагается, что класс Person содержит поля passport и address. Passport содержит все паспортные данные человека.

2020-04-08 20:32 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/models/Passport.java
> +
Количество полей не соответствует описанию класса.
Предполагалось, что паспорт содержит информацию о:
- серия и номер документа
- имя
- фамилия
- отчество
- второе имя
- день рождения
- дата выдачи документа
- наименование органа, выдавшего документ.

2020-04-08 20:32 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/models/Passport.java
> +public Passport(Person person, int seriaNambre, LocalDate happyBirsday, LocalDate dataVudachi, String ktoVudal) {
параметр **person** не используется

2020-04-08 20:32 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/models/Passport.java
> +    public Passport(Person person, int seriaNambre, LocalDate dataVudachi, String ktoVudal) {
параметр **person** не используется

2020-04-08 20:32 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/models/Passport.java
> +    public Passport(Person person, int seriaNambre, LocalDate happyBirsday) {
параметр **person** не используется

2020-04-08 20:32 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/models/Person.java
> +public class Person {
нет паспортных данных. Класс **Person** должен содержать поле **passport**.

2020-04-12 16:36 UTC, konivex requested changes
В задании сказано, что человек представляется как сущность, наделённая именем, паспортными данными и пропиской по месту жительства. Т.е. в классе Person д.б. три атрибута, а точнее даже два составных — паспортные данные и прописка, т.к. имя входит в паспортные данные. Это и д.б. отражено в коде.

Исправьте в соответствии с моими замечаниями и замечаниями Кирилла Дмитриевича.

2020-04-18 11:36 UTC, konivex approved these changes
Зачтено.

2020-04-18 13:41 UTC, closed without merging